# Generated by Django 5.0.4 on 2024-05-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('photo', models.ImageField(blank=True, upload_to='products_images')),
                ('description', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=1, max_digits=4)),
                ('country', models.CharField(max_length=40)),
                ('nutritional_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('manufactures', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
            ],
        ),
    ]
