# Generated by Django 5.0.4 on 2024-05-19 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('product_id',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
